# Generated by Django 4.1.4 on 2023-01-08 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followers', '0002_posts'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followlist',
            name='followedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followedBy', to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
        migrations.AlterField(
            model_name='followlist',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL, to_field='email'),
        ),
    ]
