# Generated by Django 4.1.4 on 2023-01-08 11:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followers', '0003_alter_followlist_followedby_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='followlist',
            name='following',
        ),
        migrations.AddField(
            model_name='followlist',
            name='followedByUname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='followlist',
            name='followingByUname',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='followlist',
            name='followedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followedBy', to=settings.AUTH_USER_MODEL),
        ),
    ]
