# Generated by Django 4.1.4 on 2023-01-08 11:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followers', '0005_followlist_following'),
    ]

    operations = [
        migrations.AlterField(
            model_name='followlist',
            name='followedBy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followedByr', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='followlist',
            name='following',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followingr', to=settings.AUTH_USER_MODEL),
        ),
    ]
