# Generated by Django 4.1.4 on 2023-01-10 08:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0007_posts_username_alter_posts_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='posts',
            name='visibility',
            field=models.BooleanField(default=True),
        ),
    ]
