# Generated by Django 4.1.4 on 2023-01-11 09:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0008_alter_posts_visibility'),
    ]

    operations = [
        migrations.RenameField(
            model_name='followlist',
            old_name='followedByUname',
            new_name='firstUname',
        ),
        migrations.RenameField(
            model_name='followlist',
            old_name='followedBy',
            new_name='firstuser',
        ),
        migrations.RenameField(
            model_name='followlist',
            old_name='followingByUname',
            new_name='secondUname',
        ),
        migrations.RenameField(
            model_name='followlist',
            old_name='following',
            new_name='seconduser',
        ),
    ]
