# Generated by Django 4.1.4 on 2023-01-26 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0009_rename_followedbyuname_followlist_firstuname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='likeCount',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
