# Generated by Django 4.1.4 on 2023-01-26 05:49

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followers', '0010_posts_likecount'),
    ]

    operations = [
        migrations.CreateModel(
            name='Likes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('likedCount', models.IntegerField(blank=True, null=True)),
                ('isLiked', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('likedPost', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='followers.posts')),
            ],
        ),
    ]
