# Generated by Django 4.1.4 on 2023-01-26 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0011_likes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='likes',
            name='likedCount',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
