# Generated by Django 4.1.4 on 2023-01-26 10:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('followers', '0012_alter_likes_likedcount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='likes',
            name='likedCount',
        ),
        migrations.RemoveField(
            model_name='likes',
            name='isLiked',
        ),
        migrations.AddField(
            model_name='likes',
            name='isLiked',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
