# Generated by Django 4.1.4 on 2023-02-13 09:46

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('followers', '0013_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='time',
            field=models.DateTimeField(blank=datetime.datetime(2023, 2, 13, 15, 16, 22, 39434), default='2023-02-13 15:15:41.835063'),
            preserve_default=False,
        ),
    ]
