# Generated by Django 4.1.3 on 2022-11-30 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSide', '0002_remove_user_active_remove_user_admin_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='demo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=250)),
            ],
        ),
    ]
