# Generated by Django 4.1.3 on 2022-12-01 10:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSide', '0003_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='admin',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='user',
            name='staff',
            field=models.BooleanField(default=False),
        ),
    ]
