# Generated by Django 4.1.4 on 2022-12-29 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('adminSide', '0006_user_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='active',
        ),
    ]
