# Generated by Django 4.1.4 on 2023-01-02 10:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSide', '0008_user_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='active',
            field=models.BooleanField(default=True),
        ),
    ]
