# Generated by Django 4.1.4 on 2023-01-08 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSide', '0009_alter_user_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='dob',
            field=models.DateField(blank=True, default='2000-12-12'),
        ),
    ]
