# Generated by Django 4.1.4 on 2023-01-08 07:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSide', '0010_user_dob'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_name',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
