# Generated by Django 4.1.4 on 2023-01-08 10:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSide', '0012_remove_user_id_alter_user_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='id',
            field=models.BigIntegerField(auto_created=True, default=1),
            preserve_default=False,
        ),
    ]
