# Generated by Django 4.1.4 on 2023-01-08 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSide', '0013_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigIntegerField(auto_created=True, unique=True),
        ),
    ]
