# Generated by Django 4.1.4 on 2023-01-08 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminSide', '0014_alter_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.EmailField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='id',
            field=models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID'),
        ),
    ]
